"""crear tablas iniciales marcas y autos

Revision ID: 9552472da095
Revises: 
Create Date: 2026-10-08 18:16:36.419525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9552472da095'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marcas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marcas_nombre'), ['nombre'], unique=True)

    op.create_table('autos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('autos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_autos_marca_id'), ['marca_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autos_marca_id'))
        batch_op.drop_index(batch_op.f('ix_autos_id'))

    op.drop_table('autos')
    with op.batch_alter_table('marcas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marcas_nombre'))

    op.drop_table('marcas')
    # ### end Alembic commands ###
